### ISSUE TITLE
How long does it takes for training the model?

### ISSUE THREAD

**Issue by Yiir-1** [JeffWang987/OpenOccupancy#1]
Thanks for the good work! I want to know how long does it takes for training the model using 8 GPUs?
And which GPU do you use to train the model?

**Comment by JeffWang987** [comment]
> Thanks for the good work! I want to know how long does it takes for training the model using 8 GPUs. And which GPU do you use to train the model?

We use 8 A100 GPUs to train the models, and the training time for camera-based, LiDAR-based and multimodal baselines are approximately 20h, 12h, 25h. For camera-based CONet, LiDAR-based CONet and multimodal CONet, the training time are 34h, 20h, 36h. Note that the **validation** is enabled per epoch, so you can disable it for fast training.
