### ISSUE TITLE
About the occupancy data

### ISSUE THREAD

**Issue by NorthSummer** [JeffWang987/OpenOccupancy#11]
Hi! I want to ask what is stored in the provided occupancy dataset, because I find it very difficult to visualize as point clouds. And is there any loader for the provided data?

**Comment by JeffWang987** [comment]
> Hi! I want to ask what is stored in the provided occupancy dataset, because I find it very difficult to visualize as point clouds. And is there any loader for the provided data?

We provide occupancy labels in each npy file. The shape of the npy file is [N,4], where N is the number of occupancy, and 4 is 3 indices (z,y,x) and 1 semantic label. For visualization, you can refer to https://github.com/astra-vision/MonoScene#visualization

**Comment by NorthSummer** [comment]
Thanks, the problem's been solved

**Comment by vanelyang** [comment]
> Thanks, the problem's been solved

Excuse me, could you please provide the visualization code? I don't know how to visualize it. Thank you very much.
