### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by shenxiaowrj** [JeffWang987/OpenOccupancy#12]
I regenerated the ground_truth with the latest version of the code.
And i use the 
python ./tools/test.py ./projects/configs/baselines/CAM-R50_img1600_128x128x10.py ./work_dirs/CAM-R50_img1600_128x128x10/latest.pth --deterministic --eval bbox
to test the c-baseline model.
The weights I used were obtained after training two epochs. The test exceeded the set maximum test dataset length.
![711679b78e19efcadfc126f86e6c84b](https://user-images.githubusercontent.com/100119921/225505782-00fa95ba-5e5d-4695-9253-34a6e971dfd8.jpg)
How can I solve this problem?
Thanks.

**Comment by JeffWang987** [comment]
It is a small updating bug of the ProgressBar, which does not influence the evaluation performance.
We have fixed it, please pull the latest code.

**Comment by shenxiaowrj** [comment]
Thanks!
The previous issue was solved. But the testing phase still didn't go smoothly. It encountered the following issues.

6019/6019, 0.8 task/s, elapsed: 7264s, ETA:     0sTraceback (most recent call last):
  File "./tools/test.py", line 278, in &lt;module&gt;
    main()
  File "./tools/test.py", line 275, in main
    print(dataset.evaluate(outputs, **eval_kwargs))
  File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/data/OpenOccupancy/projects/occ_plugin/datasets/nuscenes_occ_dataset.py", line 130, in evaluate
    ious = cm_to_ious(evaluation_semantic)
  File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/data/OpenOccupancy/projects/occ_plugin/utils/formating.py", line 8, in cm_to_ious
    tp = cm[i, i]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
![7294cd5fc8f0d06605da38a75b8ce60](https://user-images.githubusercontent.com/100119921/225611467-64dfc91d-0045-47fd-bf78-d75b13b0dac3.jpg)

**Comment by shenxiaowrj** [comment]
> It is a small updating bug of the ProgressBar, which does not influence the evaluation performance. We have fixed it, please pull the latest code.

Thanks!
The previous issue was solved. But the testing phase still didn't go smoothly. It encountered the following issues.

6019/6019, 0.8 task/s, elapsed: 7264s, ETA: 0sTraceback (most recent call last):
File "./tools/test.py", line 278, in <module>
main()
File "./tools/test.py", line 275, in main
print(dataset.evaluate(outputs, **eval_kwargs))
File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/data/OpenOccupancy/projects/occ_plugin/datasets/nuscenes_occ_dataset.py", line 130, in evaluate
ious = cm_to_ious(evaluation_semantic)
File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/data/OpenOccupancy/projects/occ_plugin/utils/formating.py", line 8, in cm_to_ious
tp = cm[i, i]
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
![7294cd5fc8f0d06605da38a75b8ce60](https://user-images.githubusercontent.com/100119921/225611576-9b4c9dcd-c600-4411-b5f0-d0cea19f4343.jpg)

**Comment by shenxiaowrj** [comment]
> 

Thanks!

**Comment by dzp17** [comment]
> > It is a small updating bug of the ProgressBar, which does not influence the evaluation performance. We have fixed it, please pull the latest code.
> 
> Thanks! The previous issue was solved. But the testing phase still didn't go smoothly. It encountered the following issues.
> 
> 6019/6019, 0.8 task/s, elapsed: 7264s, ETA: 0sTraceback (most recent call last): File "./tools/test.py", line 278, in main() File "./tools/test.py", line 275, in main print(dataset.evaluate(outputs, **eval_kwargs)) File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/data/OpenOccupancy/projects/occ_plugin/datasets/nuscenes_occ_dataset.py", line 130, in evaluate ious = cm_to_ious(evaluation_semantic) File "/media/re/2384a6b4-4dae-400d-ad72-9b7044491b55/data/OpenOccupancy/projects/occ_plugin/utils/formating.py", line 8, in cm_to_ious tp = cm[i, i] IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed ![7294cd5fc8f0d06605da38a75b8ce60](https://user-images.githubusercontent.com/100119921/225611576-9b4c9dcd-c600-4411-b5f0-d0cea19f4343.jpg)

Hi,I encountered the same error as you, have you solved it?
