### ISSUE TITLE
Question about Train camera-based baseline

### ISSUE THREAD

**Issue by promesse** [JeffWang987/OpenOccupancy#14]
![image](https://user-images.githubusercontent.com/26239060/225622879-e79bd65a-2d23-4746-a2d3-5780332ba0e5.png)

Have you ever met this problem? How Can I fix it?

**Comment by JeffWang987** [comment]
Have you done step 8 in [installation](https://github.com/JeffWang987/OpenOccupancy/blob/main/docs/install.md)?

**Comment by promesse** [comment]
> Have you done step 8 in [installation](https://github.com/JeffWang987/OpenOccupancy/blob/main/docs/install.md)?

sorry paste the wrong pic
i have update the question pic

**Comment by 0w0h0y** [comment]
This can be fixed by setting `workers_per_gpu=0`

**Comment by promesse** [comment]
> This can be fixed by setting `workers_per_gpu=0`

thanks a lot, it works.
so if workers_per_gpu=0, the speed will be slower?
