### ISSUE TITLE
Question about label pkl files

### ISSUE THREAD

**Issue by levell96evel** [JeffWang987/OpenOccupancy#15]
At first, Thanks for your stunning work!
I used Mayavi to visualize some scenes, and found that there are a lot of noise points with un-noise labels in the visulization, just like below
![image](https://user-images.githubusercontent.com/48512589/226393086-0df7af63-a313-4c08-bce2-eff7e2a6acd5.png)
front_left image
![image](https://user-images.githubusercontent.com/48512589/226393214-8b0955cc-53d7-414d-908e-1b76c8754e8a.png)
front image
![image](https://user-images.githubusercontent.com/48512589/226393249-b7c01d50-f0e4-4b4a-ada0-ea9380d7ebcf.png)
This situation exists in a large number of labeling scenarios. It seems that the label files were "pseudo labels" described in the paper.How can I solve this problem?

**Comment by JeffWang987** [comment]
We recommend to use the annotation-v0.1, please refer to prepare-dataset for more details.

**Comment by vanelyang** [comment]
> At first, Thanks for your stunning work! I used Mayavi to visualize some scenes, and found that there are a lot of noise points with un-noise labels in the visulization, just like below ![image](https://user-images.githubusercontent.com/48512589/226393086-0df7af63-a313-4c08-bce2-eff7e2a6acd5.png) front_left image ![image](https://user-images.githubusercontent.com/48512589/226393214-8b0955cc-53d7-414d-908e-1b76c8754e8a.png) front image ![image](https://user-images.githubusercontent.com/48512589/226393249-b7c01d50-f0e4-4b4a-ada0-ea9380d7ebcf.png) This situation exists in a large number of labeling scenarios. It seems that the label files were "pseudo labels" described in the paper.How can I solve this problem?

Excuse me, could you please provide the visualization code? I don't know how to visualize it.  Thank you very much.
