### ISSUE TITLE
Any attempts on multi-frame training?

### ISSUE THREAD

**Issue by zehuichen123** [JeffWang987/OpenOccupancy#17]
Hi, I am trying to adapt BEVDet4D style multi-frame inputs to OpenOcc. However, the results are not satisfying (with a slight performance drop: 8.7->8.6 mIoU). I am wondering if you have tried this. Thanks.

**Comment by JeffWang987** [comment]
I haven't tried it yet. Can you provide detailed metrics for each category to explain the counterintuitive performance drop? Specifically, I'm curious if the multi-frame setting overfits to large-structured regions such as roads or is negatively impacted by moving objects like cars.

**Comment by zehuichen123** [comment]
Sorry. I wrote some bugs in the code. The multi-frame training can improve performance.

**Comment by chenzyhust** [comment]
> May I ask how much multi-frame training has improved?

**Comment by chenzyhust** [comment]
> Sorry. I wrote some bugs in the code. The multi-frame training can improve performance.

May I ask how much multi-frame training has improved?
