### ISSUE TITLE
Visualization 

### ISSUE THREAD

**Issue by dikubab** [JeffWang987/OpenOccupancy#18]
Please can you provide further guidance on how to visualize the occupancy.

**Comment by Junyu-Z** [comment]
+1

**Comment by Qinyu-Z** [comment]
+1

**Comment by Monssica** [comment]
+1

**Comment by JeffWang987** [comment]
Sorry for the late reply. We've been busy with other projects.

The visualization code  (tools/misc/visualizer.py) is now uploaded. Feel free to modify it as you need.
