### ISSUE TITLE
An error was encountered when generating gen_depth_gt

### ISSUE THREAD

**Issue by chenzyhust** [JeffWang987/OpenOccupancy#2]
Found that the provided nuscenes_occ_infos_train.pkl file does not match the information required by gen_depth_gt?Running the program will directly report error

**Comment by JeffWang987** [comment]
We will check it ASAP

**Comment by JeffWang987** [comment]
> 

sorry for the mistake, we have corrected the depth generation code (tools/gen_data/gen_depth_gt.py).
