### ISSUE TITLE
The loss problems for Multimodal CONet log file

### ISSUE THREAD

**Issue by Young98CN** [JeffWang987/OpenOccupancy#21]
![image](https://user-images.githubusercontent.com/71887148/233312580-b3309ac2-cef0-413f-a10e-9be1d8428d06.png)
Hi, I have a question about the Multimodal CONet log file(download in your official link). As the figure shows, all of the losses remained at 1.0000. Is that true? I would like to know the change process of loss, whether I need to adjust the source code？

**Comment by JeffWang987** [comment]
Plz refer to https://github.com/JeffWang987/OpenOccupancy/issues/4
