### ISSUE TITLE
Upload pretrainted models to google drive

### ISSUE THREAD

**Issue by lexavtanke** [JeffWang987/OpenOccupancy#24]
Hi, thank you very much for your great work. Is there any plan to upload weights of trained models to google drive?
Because It is not so easy to download them from baidu disk without Chinese telephone number.

**Comment by JeffWang987** [comment]
uploaded, here:

https://drive.google.com/file/d/1rqzMy0GDsvTXNMh4Zk2WsPBFXd0jobH0/view?usp=sharing
