### ISSUE TITLE
questions about pretrained model

### ISSUE THREAD

**Issue by aoyanl** [JeffWang987/OpenOccupancy#27]
Are there some problems with the pretrained model？  I evaluate the model with camera-based-Conet.pth，but IoU and mIoU are much lower than that published in the paper.
'SC_non-empty': 0.17, 'SSC_fine_free': 0.976, 'SSC_fine_barrier': 0.041, 'SSC_fine_bicycle': 0.031, 'SSC_fine_bus': 0.073, 'SSC_fine_car': 0.125, 'SSC_fine_construction_vehicle': 0.047, 'SSC_fine_motorcycle': 0.055, 'SSC_fine_pedestrian': 0.093, 'SSC_fine_traffic_cone': 0.07, 'SSC_fine_trailer': 0.02, 'SSC_fine_truck': 0.082, 'SSC_fine_driveable_surface': 0.309, 'SSC_fine_other_flat': 0.134, 'SSC_fine_sidewalk': 0.143, 'SSC_fine_terrain': 0.137, 'SSC_fine_manmade': 0.014, 'SSC_fine_vegetation': 0.027, 'SSC_fine_mean': 0.088}

**Comment by JeffWang987** [comment]
Sorry for the late response, you can refer to the training logs for evaluation results.
