### ISSUE TITLE
Discrepancy in z-range between paper and config

### ISSUE THREAD

**Issue by patrick-llgc** [JeffWang987/OpenOccupancy#28]
Hi Xiaofeng/Jeff, 

First of all, great work for putting together such a solid project for semantic occupancy prediction. The academia needs such a dataset and benchmark.

There is a discrepancy between the Z-range described in the paper and that in the config. 

<img width="968" alt="image" src="https://github.com/JeffWang987/OpenOccupancy/assets/32552339/42e7d3dd-429f-4235-a6fa-3fabe2f6c2d2">
<img width="348" alt="image" src="https://github.com/JeffWang987/OpenOccupancy/assets/32552339/01ddcfe4-031d-43b4-9670-cacddde8c631">

It seems to me that [-5m, 3m] should be the correct one, as the Z origin is on top of the car (aligned with the top lidar mounting position). Could you confirm?

Thanks,
Patrick

**Comment by JeffWang987** [comment]
Hi Patrick, thank you for your attention to our work. For your concern, we set [-5m, 3m] as the  Z-range in the OpenOccupancy benchmark, and [-3m, 5m] is a writing typo. We appreciate that you point out the problem.
