### ISSUE TITLE
The shape of occupancy gt

### ISSUE THREAD

**Issue by aoyanl** [JeffWang987/OpenOccupancy#31]
Hi, I am wondering if the shape of the gt is W*H*D or H*W*D?

**Comment by JeffWang987** [comment]
The gt is stored with the shape  [z y x cls] or [D,H,W,cls], but in the [dataloader](https://github.com/JeffWang987/OpenOccupancy/blob/main/projects/occ_plugin/datasets/pipelines/loading.py), we change the shape as [x,y,z,cls], which results in [W,H,D,cls]
