### ISSUE TITLE
Is `occ_pooling` support z-dim >1 ?

### ISSUE THREAD

**Issue by OrangeSodahub** [JeffWang987/OpenOccupancy#34]
Great work! I would like to know that if the `occ_pooling` support pooling multiple frustums into whole voxel with z-dim >1? Which is different from pure LSS.

https://github.com/JeffWang987/OpenOccupancy/blob/2c57112495bc071f678c764dbe24c06c2ddb243b/projects/occ_plugin/occupancy/image2bev/ViewTransformerLSSVoxel.py#L97-L121

**Comment by JeffWang987** [comment]
Yes, the **occ_pool** operation pools multiple frustums into a voxel feature with shape of [B, C, Z, X, Y]. https://github.com/JeffWang987/OpenOccupancy/blob/2c57112495bc071f678c764dbe24c06c2ddb243b/projects/occ_plugin/occupancy/image2bev/ViewTransformerLSSVoxel.py#L118
