### ISSUE TITLE
Batch size in training stage

### ISSUE THREAD

**Issue by Jeffery-J** [JeffWang987/OpenOccupancy#35]
HI, I find that _samples_per_gpu_ is set as 1 in all your config, so is there any reason to do so? I think the memory is enough in some tasks if you set _samples_per_gpu_ to 2 or 4.

**Comment by JeffWang987** [comment]
All models are trained with a batch size of 8 (one for each GPU) for fair comparison. And you can increase batch size during training.

**Comment by Jeffery-J** [comment]
Get it, thanks !

**Comment by annopackage** [comment]
Hi, how much memory does it need if using resnet50 and 6 cameras? If setting larger batch size, can we get better results?
