### ISSUE TITLE
What is the actual voxel grid range?

### ISSUE THREAD

**Issue by ruoyuwangeel4930** [JeffWang987/OpenOccupancy#36]
Dear authors,

In the config files, I saw: point_cloud_range = [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]. I assume that the occupancy range for z is -5.0 to 3.0. However, this is different from what is reported in the paper: -3.0 to 5.0. Could you please provide some explanation? Thanks a lot.

Another question is: What is the origin of the voxel grid coordinate system? Is it the same as the car coordinate system or the lidar coordinate system?

**Comment by JeffWang987** [comment]
The voxel z range is (-5,3). Note that (-3,5)is a writing typo in the preprinted paper. And the coordinate is align with LiDAR system.在 2023年7月30日，13:24，Ruoyu Wang ***@***.***> 写道：﻿
Dear authors,
In the config files, I saw: point_cloud_range = [-51.2, -51.2, -5.0, 51.2, 51.2, 3.0]. I assume that the occupancy range for z is -5.0 to 3.0. However, this is different from what is reported in the paper: -3.0 to 5.0. Could you please provide some explanation? Thanks a lot.
Another question is: What is the origin of the voxel grid coordinate system? Is it the same as the car coordinate system or the lidar coordinate system?

**Comment by ruoyuwangeel4930** [comment]
Thanks a lot for your answering!
