### ISSUE TITLE
ValueError: Pool not running

### ISSUE THREAD

**Issue by shenxiaowrj** [JeffWang987/OpenOccupancy#8]
After I've been running gen_depth_gt.py for a while, and I've generated some ground truths (maybe not all), I suddenly get the following error:
Traceback (most recent call last):
  File "./tools/gen_data/gen_depth_gt.py", line 137, in &lt;module&gt;
    po.apply_async(func=worker, args=(info, ))
  File "/home/re/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/pool.py", line 455, in apply_async
    self._check_running()
  File "/home/re/anaconda3/envs/open-mmlab/lib/python3.8/multiprocessing/pool.py", line 350, in _check_running
    raise ValueError("Pool not running")
ValueError: Pool not running

What is causing this problem? Is my CPU performance insufficient or is there some bug in the project code? I sincerely hope that you could help.Thank you!

**Comment by qihao-plus** [comment]
git pull latest code.

**Comment by shenxiaowrj** [comment]
> 
Thanks,I'll try it now.

**Comment by shenxiaowrj** [comment]
> git pull latest code. ref #2

I use the latest version of the code and then rerun it, but I get the same error, the error message and the key code snippet are shown in the figure below:
![0d896c3a185bd1cbafccc9dca8e5777](https://user-images.githubusercontent.com/100119921/224890010-2d5086b5-f0e1-430d-aa0c-f741184ce0b0.jpg)

**Comment by promesse** [comment]
i meet the same problrm

**Comment by JeffWang987** [comment]
Use the code below to localize the error.
![image](https://user-images.githubusercontent.com/49095445/224968818-c7b453d3-25f5-436b-8908-3c2e645e47c2.png)

**Comment by promesse** [comment]
> > git pull latest code. ref #2
> 
> I use the latest version of the code and then rerun it, but I get the same error, the error message and the key code snippet are shown in the figure below: ![0d896c3a185bd1cbafccc9dca8e5777](https://user-images.githubusercontent.com/100119921/224890010-2d5086b5-f0e1-430d-aa0c-f741184ce0b0.jpg)

Hi brother I fixed it by set a new po. I think maybe the same instance  po can't be closed and then used.
![截图](https://user-images.githubusercontent.com/26239060/224989398-7b5483b3-7425-4bf8-a73a-f390f7a9a371.JPG)

**Comment by shenxiaowrj** [comment]
> > > git pull latest code. ref #2
> > 
> > 
> > I use the latest version of the code and then rerun it, but I get the same error, the error message and the key code snippet are shown in the figure below: ![0d896c3a185bd1cbafccc9dca8e5777](https://user-images.githubusercontent.com/100119921/224890010-2d5086b5-f0e1-430d-aa0c-f741184ce0b0.jpg)
> 
> Hi brother I fixed it by set a new po. I think maybe the same instance po can't be closed and then used. ![截图](https://user-images.githubusercontent.com/26239060/224989398-7b5483b3-7425-4bf8-a73a-f390f7a9a371.JPG)

Thanks! I also offer my methodology. I split the generation of the ground truth for TRAIN and Val into two phases. In this way, no errors are encountered.
![ba0ac9cebb9e5361a713575266cabb9](https://user-images.githubusercontent.com/100119921/225028003-441d06f6-7507-46e1-819a-dd4b6cd96550.jpg)

**Comment by shenxiaowrj** [comment]
> 

Thanks!

**Comment by shenxiaowrj** [comment]
> Use the code below to localize the error. ![image](https://user-images.githubusercontent.com/49095445/224968818-c7b453d3-25f5-436b-8908-3c2e645e47c2.png)

Thanks!
